[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.2
    knolleary/PubSubClient@^2.8
    nanopb/Nanopb@^0.4.8
monitor_speed = 115200
build_flags =
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCONFIG_BT_NIMBLE_PINNED_TO_CORE=0
    -DMQTT_MAX_PACKET_SIZE=512

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=c++17
    -DNATIVE_TEST
