/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_APPINFOMATIONDATA_PB_H_INCLUDED
#define PB_PROTO_APPINFOMATIONDATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _APPDtuInfoMO {
    bool has_device_kind;
    int32_t device_kind;
    bool has_dtu_sw_version;
    int32_t dtu_sw_version;
    bool has_dtu_hw_version;
    int32_t dtu_hw_version;
    bool has_dfs;
    int64_t dfs;
    bool has_shls;
    int64_t shls;
    bool has_type;
    int32_t type;
    pb_callback_t enc_rand;
} APPDtuInfoMO;

typedef struct _APPInfoDataResDTO {
    pb_callback_t time_ymd_hms;
    bool has_offset;
    int32_t offset;
    bool has_current_package;
    int32_t current_package;
    bool has_timestamp;
    uint32_t timestamp;
} APPInfoDataResDTO;

typedef struct _APPInfoDataReqDTO {
    bool has_dtu_serial_number;
    char dtu_serial_number[32];
    bool has_timestamp;
    uint32_t timestamp;
    bool has_device_number;
    int32_t device_number;
    bool has_package_number;
    int32_t package_number;
    bool has_current_package;
    int32_t current_package;
    bool has_dtu_info;
    APPDtuInfoMO dtu_info;
} APPInfoDataReqDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define APPDtuInfoMO_init_default                {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define APPInfoDataResDTO_init_default           {{{NULL}, NULL}, false, 0, false, 0, false, 0}
#define APPInfoDataReqDTO_init_default           {false, "", false, 0, false, 0, false, 0, false, 0, false, APPDtuInfoMO_init_default}
#define APPDtuInfoMO_init_zero                   {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define APPInfoDataResDTO_init_zero              {{{NULL}, NULL}, false, 0, false, 0, false, 0}
#define APPInfoDataReqDTO_init_zero              {false, "", false, 0, false, 0, false, 0, false, 0, false, APPDtuInfoMO_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define APPDtuInfoMO_device_kind_tag             1
#define APPDtuInfoMO_dtu_sw_version_tag          2
#define APPDtuInfoMO_dtu_hw_version_tag          3
#define APPDtuInfoMO_dfs_tag                     24
#define APPDtuInfoMO_shls_tag                    25
#define APPDtuInfoMO_type_tag                    26
#define APPDtuInfoMO_enc_rand_tag                27
#define APPInfoDataResDTO_time_ymd_hms_tag       1
#define APPInfoDataResDTO_offset_tag             2
#define APPInfoDataResDTO_current_package_tag    3
#define APPInfoDataResDTO_timestamp_tag          5
#define APPInfoDataReqDTO_dtu_serial_number_tag  1
#define APPInfoDataReqDTO_timestamp_tag          2
#define APPInfoDataReqDTO_device_number_tag      3
#define APPInfoDataReqDTO_package_number_tag     5
#define APPInfoDataReqDTO_current_package_tag    6
#define APPInfoDataReqDTO_dtu_info_tag           8

/* Struct field encoding specification for nanopb */
#define APPDtuInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    device_kind,       1) \
X(a, STATIC,   OPTIONAL, INT32,    dtu_sw_version,    2) \
X(a, STATIC,   OPTIONAL, INT32,    dtu_hw_version,    3) \
X(a, STATIC,   OPTIONAL, SINT64,   dfs,              24) \
X(a, STATIC,   OPTIONAL, SINT64,   shls,             25) \
X(a, STATIC,   OPTIONAL, INT32,    type,             26) \
X(a, CALLBACK, OPTIONAL, BYTES,    enc_rand,         27)
#define APPDtuInfoMO_CALLBACK pb_default_field_callback
#define APPDtuInfoMO_DEFAULT NULL

#define APPInfoDataResDTO_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, BYTES,    time_ymd_hms,      1) \
X(a, STATIC,   OPTIONAL, INT32,    offset,            2) \
X(a, STATIC,   OPTIONAL, INT32,    current_package,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   timestamp,         5)
#define APPInfoDataResDTO_CALLBACK pb_default_field_callback
#define APPInfoDataResDTO_DEFAULT NULL

#define APPInfoDataReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   dtu_serial_number,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   timestamp,         2) \
X(a, STATIC,   OPTIONAL, INT32,    device_number,     3) \
X(a, STATIC,   OPTIONAL, INT32,    package_number,    5) \
X(a, STATIC,   OPTIONAL, INT32,    current_package,   6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dtu_info,          8)
#define APPInfoDataReqDTO_CALLBACK NULL
#define APPInfoDataReqDTO_DEFAULT NULL
#define APPInfoDataReqDTO_dtu_info_MSGTYPE APPDtuInfoMO

extern const pb_msgdesc_t APPDtuInfoMO_msg;
extern const pb_msgdesc_t APPInfoDataResDTO_msg;
extern const pb_msgdesc_t APPInfoDataReqDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define APPDtuInfoMO_fields &APPDtuInfoMO_msg
#define APPInfoDataResDTO_fields &APPInfoDataResDTO_msg
#define APPInfoDataReqDTO_fields &APPInfoDataReqDTO_msg

/* Maximum encoded size of messages (where known) */
/* APPDtuInfoMO_size depends on runtime parameters */
/* APPInfoDataResDTO_size depends on runtime parameters */
/* APPInfoDataReqDTO_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
