/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/APPInfomationData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(APPDtuInfoMO, APPDtuInfoMO, AUTO)


PB_BIND(APPInfoDataResDTO, APPInfoDataResDTO, AUTO)


PB_BIND(APPInfoDataReqDTO, APPInfoDataReqDTO, AUTO)



