/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/CommCmd.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CommandResDTO, CommandResDTO, AUTO)


PB_BIND(CommandReqDTO, CommandReqDTO, AUTO)



