/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_COMMCMD_PB_H_INCLUDED
#define PB_PROTO_COMMCMD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CommandResDTO {
    bool has_dtu_sn;
    char dtu_sn[32];
    bool has_time;
    int32_t time;
    bool has_action;
    int32_t action;
    bool has_package_now;
    int32_t package_now;
    bool has_err_code;
    int32_t err_code;
    bool has_tid;
    int64_t tid;
} CommandResDTO;

typedef struct _CommandReqDTO {
    bool has_time;
    int32_t time;
    bool has_action;
    int32_t action;
    bool has_dev_kind;
    int32_t dev_kind;
    bool has_package_nub;
    int32_t package_nub;
    bool has_package_now;
    int32_t package_now;
    bool has_tid;
    int64_t tid;
    bool has_data;
    char data[64];
    bool has_es_to_sn;
    char es_to_sn[32];
} CommandReqDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CommandResDTO_init_default               {false, "", false, 0, false, 0, false, 0, false, 0, false, 0}
#define CommandReqDTO_init_default               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, ""}
#define CommandResDTO_init_zero                  {false, "", false, 0, false, 0, false, 0, false, 0, false, 0}
#define CommandReqDTO_init_zero                  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, ""}

/* Field tags (for use in manual encoding/decoding) */
#define CommandResDTO_dtu_sn_tag                 1
#define CommandResDTO_time_tag                   2
#define CommandResDTO_action_tag                 3
#define CommandResDTO_package_now_tag            4
#define CommandResDTO_err_code_tag               5
#define CommandResDTO_tid_tag                    6
#define CommandReqDTO_time_tag                   1
#define CommandReqDTO_action_tag                 2
#define CommandReqDTO_dev_kind_tag               3
#define CommandReqDTO_package_nub_tag            4
#define CommandReqDTO_package_now_tag            5
#define CommandReqDTO_tid_tag                    6
#define CommandReqDTO_data_tag                   7
#define CommandReqDTO_es_to_sn_tag               8

/* Struct field encoding specification for nanopb */
#define CommandResDTO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   dtu_sn,            1) \
X(a, STATIC,   OPTIONAL, INT32,    time,              2) \
X(a, STATIC,   OPTIONAL, INT32,    action,            3) \
X(a, STATIC,   OPTIONAL, INT32,    package_now,       4) \
X(a, STATIC,   OPTIONAL, INT32,    err_code,          5) \
X(a, STATIC,   OPTIONAL, SINT64,   tid,               6)
#define CommandResDTO_CALLBACK NULL
#define CommandResDTO_DEFAULT NULL

#define CommandReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    time,              1) \
X(a, STATIC,   OPTIONAL, INT32,    action,            2) \
X(a, STATIC,   OPTIONAL, INT32,    dev_kind,          3) \
X(a, STATIC,   OPTIONAL, INT32,    package_nub,       4) \
X(a, STATIC,   OPTIONAL, INT32,    package_now,       5) \
X(a, STATIC,   OPTIONAL, SINT64,   tid,               6) \
X(a, STATIC,   OPTIONAL, STRING,   data,              7) \
X(a, STATIC,   OPTIONAL, STRING,   es_to_sn,          8)
#define CommandReqDTO_CALLBACK NULL
#define CommandReqDTO_DEFAULT NULL

extern const pb_msgdesc_t CommandResDTO_msg;
extern const pb_msgdesc_t CommandReqDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CommandResDTO_fields &CommandResDTO_msg
#define CommandReqDTO_fields &CommandReqDTO_msg

/* Maximum encoded size of messages (where known) */
#define CommandReqDTO_size                       164
#define CommandResDTO_size                       88
#define PROTO_COMMCMD_PB_H_MAX_SIZE              CommandReqDTO_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
