/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/RealDataNew.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PvMO, PvMO, AUTO)


PB_BIND(SGSMO, SGSMO, AUTO)


PB_BIND(RealDataNewResDTO, RealDataNewResDTO, AUTO)


PB_BIND(RealDataNewReqDTO, RealDataNewReqDTO, 2)



