/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_REALDATANEW_PB_H_INCLUDED
#define PB_PROTO_REALDATANEW_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PvMO {
    bool has_serial_number;
    int64_t serial_number;
    bool has_port_number;
    int32_t port_number;
    bool has_voltage;
    int32_t voltage;
    bool has_current;
    int32_t current;
    bool has_power;
    int32_t power;
    bool has_energy_total;
    int32_t energy_total;
    bool has_energy_daily;
    int32_t energy_daily;
    bool has_error_code;
    int32_t error_code;
} PvMO;

typedef struct _SGSMO {
    bool has_serial_number;
    int64_t serial_number;
    bool has_firmware_version;
    int32_t firmware_version;
    bool has_voltage;
    int32_t voltage;
    bool has_frequency;
    int32_t frequency;
    bool has_active_power;
    int32_t active_power;
    bool has_reactive_power;
    int32_t reactive_power;
    bool has_current;
    int32_t current;
    bool has_power_factor;
    int32_t power_factor;
    bool has_temperature;
    int32_t temperature;
    bool has_warning_number;
    int32_t warning_number;
    bool has_crc_checksum;
    int32_t crc_checksum;
    bool has_link_status;
    int32_t link_status;
    bool has_power_limit;
    int32_t power_limit;
} SGSMO;

typedef PB_BYTES_ARRAY_T(6) RealDataNewResDTO_time_ymd_hms_t;
typedef struct _RealDataNewResDTO {
    bool has_time_ymd_hms;
    RealDataNewResDTO_time_ymd_hms_t time_ymd_hms;
    bool has_cp;
    int32_t cp;
    bool has_error_code;
    int32_t error_code;
    bool has_offset;
    int32_t offset;
    bool has_time;
    int32_t time;
} RealDataNewResDTO;

typedef struct _RealDataNewReqDTO {
    bool has_device_serial_number;
    char device_serial_number[32];
    bool has_timestamp;
    int32_t timestamp;
    bool has_ap;
    int32_t ap;
    bool has_cp;
    int32_t cp;
    bool has_firmware_version;
    int32_t firmware_version;
    bool has_sgs_data;
    SGSMO sgs_data;
    pb_size_t pv_data_count;
    PvMO pv_data[4];
    bool has_dtu_power;
    uint64_t dtu_power;
    bool has_dtu_daily_energy;
    uint64_t dtu_daily_energy;
} RealDataNewReqDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PvMO_init_default                        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define SGSMO_init_default                       {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define RealDataNewResDTO_init_default           {false, {0, {0}}, false, 0, false, 0, false, 0, false, 0}
#define RealDataNewReqDTO_init_default           {false, "", false, 0, false, 0, false, 0, false, 0, false, SGSMO_init_default, 0, {PvMO_init_default, PvMO_init_default, PvMO_init_default, PvMO_init_default}, false, 0, false, 0}
#define PvMO_init_zero                           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define SGSMO_init_zero                          {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define RealDataNewResDTO_init_zero              {false, {0, {0}}, false, 0, false, 0, false, 0, false, 0}
#define RealDataNewReqDTO_init_zero              {false, "", false, 0, false, 0, false, 0, false, 0, false, SGSMO_init_zero, 0, {PvMO_init_zero, PvMO_init_zero, PvMO_init_zero, PvMO_init_zero}, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PvMO_serial_number_tag                   1
#define PvMO_port_number_tag                     2
#define PvMO_voltage_tag                         3
#define PvMO_current_tag                         4
#define PvMO_power_tag                           5
#define PvMO_energy_total_tag                    6
#define PvMO_energy_daily_tag                    7
#define PvMO_error_code_tag                      8
#define SGSMO_serial_number_tag                  1
#define SGSMO_firmware_version_tag               2
#define SGSMO_voltage_tag                        3
#define SGSMO_frequency_tag                      4
#define SGSMO_active_power_tag                   5
#define SGSMO_reactive_power_tag                 6
#define SGSMO_current_tag                        7
#define SGSMO_power_factor_tag                   8
#define SGSMO_temperature_tag                    9
#define SGSMO_warning_number_tag                 10
#define SGSMO_crc_checksum_tag                   11
#define SGSMO_link_status_tag                    12
#define SGSMO_power_limit_tag                    13
#define RealDataNewResDTO_time_ymd_hms_tag       1
#define RealDataNewResDTO_cp_tag                 2
#define RealDataNewResDTO_error_code_tag         3
#define RealDataNewResDTO_offset_tag             4
#define RealDataNewResDTO_time_tag               5
#define RealDataNewReqDTO_device_serial_number_tag 1
#define RealDataNewReqDTO_timestamp_tag          2
#define RealDataNewReqDTO_ap_tag                 3
#define RealDataNewReqDTO_cp_tag                 4
#define RealDataNewReqDTO_firmware_version_tag   5
#define RealDataNewReqDTO_sgs_data_tag           9
#define RealDataNewReqDTO_pv_data_tag            11
#define RealDataNewReqDTO_dtu_power_tag          12
#define RealDataNewReqDTO_dtu_daily_energy_tag   13

/* Struct field encoding specification for nanopb */
#define PvMO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, SINT64,   serial_number,     1) \
X(a, STATIC,   OPTIONAL, INT32,    port_number,       2) \
X(a, STATIC,   OPTIONAL, INT32,    voltage,           3) \
X(a, STATIC,   OPTIONAL, INT32,    current,           4) \
X(a, STATIC,   OPTIONAL, INT32,    power,             5) \
X(a, STATIC,   OPTIONAL, INT32,    energy_total,      6) \
X(a, STATIC,   OPTIONAL, INT32,    energy_daily,      7) \
X(a, STATIC,   OPTIONAL, INT32,    error_code,        8)
#define PvMO_CALLBACK NULL
#define PvMO_DEFAULT NULL

#define SGSMO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, SINT64,   serial_number,     1) \
X(a, STATIC,   OPTIONAL, INT32,    firmware_version,   2) \
X(a, STATIC,   OPTIONAL, INT32,    voltage,           3) \
X(a, STATIC,   OPTIONAL, INT32,    frequency,         4) \
X(a, STATIC,   OPTIONAL, INT32,    active_power,      5) \
X(a, STATIC,   OPTIONAL, INT32,    reactive_power,    6) \
X(a, STATIC,   OPTIONAL, INT32,    current,           7) \
X(a, STATIC,   OPTIONAL, INT32,    power_factor,      8) \
X(a, STATIC,   OPTIONAL, INT32,    temperature,       9) \
X(a, STATIC,   OPTIONAL, INT32,    warning_number,   10) \
X(a, STATIC,   OPTIONAL, INT32,    crc_checksum,     11) \
X(a, STATIC,   OPTIONAL, INT32,    link_status,      12) \
X(a, STATIC,   OPTIONAL, INT32,    power_limit,      13)
#define SGSMO_CALLBACK NULL
#define SGSMO_DEFAULT NULL

#define RealDataNewResDTO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BYTES,    time_ymd_hms,      1) \
X(a, STATIC,   OPTIONAL, INT32,    cp,                2) \
X(a, STATIC,   OPTIONAL, INT32,    error_code,        3) \
X(a, STATIC,   OPTIONAL, INT32,    offset,            4) \
X(a, STATIC,   OPTIONAL, INT32,    time,              5)
#define RealDataNewResDTO_CALLBACK NULL
#define RealDataNewResDTO_DEFAULT NULL

#define RealDataNewReqDTO_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   device_serial_number,   1) \
X(a, STATIC,   OPTIONAL, INT32,    timestamp,         2) \
X(a, STATIC,   OPTIONAL, INT32,    ap,                3) \
X(a, STATIC,   OPTIONAL, INT32,    cp,                4) \
X(a, STATIC,   OPTIONAL, INT32,    firmware_version,   5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sgs_data,          9) \
X(a, STATIC,   REPEATED, MESSAGE,  pv_data,          11) \
X(a, STATIC,   OPTIONAL, UINT64,   dtu_power,        12) \
X(a, STATIC,   OPTIONAL, UINT64,   dtu_daily_energy,  13)
#define RealDataNewReqDTO_CALLBACK NULL
#define RealDataNewReqDTO_DEFAULT NULL
#define RealDataNewReqDTO_sgs_data_MSGTYPE SGSMO
#define RealDataNewReqDTO_pv_data_MSGTYPE PvMO

extern const pb_msgdesc_t PvMO_msg;
extern const pb_msgdesc_t SGSMO_msg;
extern const pb_msgdesc_t RealDataNewResDTO_msg;
extern const pb_msgdesc_t RealDataNewReqDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PvMO_fields &PvMO_msg
#define SGSMO_fields &SGSMO_msg
#define RealDataNewResDTO_fields &RealDataNewResDTO_msg
#define RealDataNewReqDTO_fields &RealDataNewReqDTO_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_REALDATANEW_PB_H_MAX_SIZE          RealDataNewReqDTO_size
#define PvMO_size                                88
#define RealDataNewReqDTO_size                   605
#define RealDataNewResDTO_size                   52
#define SGSMO_size                               143

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
