syntax = "proto2";

message CommandResDTO {
    optional string dtu_sn      = 1;
    optional int32  time        = 2;
    optional int32  action      = 3;
    optional int32  package_now = 4;
    optional int32  err_code    = 5;
    optional sint64 tid         = 6;
}

message CommandReqDTO {
    optional int32  time        = 1;
    optional int32  action      = 2;
    optional int32  dev_kind    = 3;
    optional int32  package_nub = 4;
    optional int32  package_now = 5;
    optional sint64 tid         = 6;
    optional string data        = 7;
    optional string es_to_sn    = 8;
}
